from __future__ import print_function

import idaapi
import idautils
import idc
import sys

def GetFilePath():
    return "C:\\Games\\SkyrimMods\\RETools\\Data\\"

def IsUserName(ea):
    flags = idc.GetFlags(ea)
    functionFlags = idc.GetFunctionFlags(ea)
    if ida_bytes.isFunc(flags) and (functionFlags & idc.FUNC_LIB or functionFlags & idc.FUNC_THUNK):
        return False
    return idc.hasUserName(flags)

def IsAutoGenerated(value):
    if value.startswith("jpt_") or value.startswith("def_") or value.startswith("funcs_"):
        return True
    if value.find("__crt") != -1:
        return True
    if not value.startswith("??_") and value.find("@std") != -1:
        return True
    return False

def GetStr(num):
    return "%X" % num

if __name__ == '__main__':
    if idaapi.IDA_SDK_VERSION >= 740:
        sys.exit("This script is not compatible with IDAPython 7.4+")

    print("Beginning export\n")

    handle = open(GetFilePath() + "idanames.txt", "w")
    handle.truncate()
    for key, value in Names():
        if IsUserName(key) != True:
            continue
        if IsAutoGenerated(value):
            continue
        handle.write(GetStr(key))
        handle.write("\t")
        handle.write(value)
        handle.write("\t")
        name_str = Demangle(value, GetLongPrm(INF_SHORT_DN))
        if name_str:
            handle.write(name_str)
        handle.write("\n")
    handle.close()

    print("Done with export\n")
